FROM resin/raspberrypi3-node:latest
MAINTAINER Tasos Oikonomidis
WORKDIR /usr/src/app

LABEL description="A linux C++ build environment."

RUN apt-get update && apt-get install -y \
  gcc \
  clang \
  cmake \
  libgtest-dev \
  libgoogle-glog-dev \
  libboost-all-dev \
  g++ `#Fb folly deps` \
  automake \
  autoconf \
  autoconf-archive \
  libtool \
  libboost-all-dev \
  libevent-dev \
  libdouble-conversion-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  liblz4-dev \
  liblzma-dev \
  libsnappy-dev \
  make \
  zlib1g-dev \
  binutils-dev \
  libjemalloc-dev \
  libssl-dev \
  libiberty-dev

ENV LD_LIBRARY_PATH=/libs
ENV CPLUS_INCLUDE_PATH=/libs/include


COPY LoRaWAN_P2P_send_packets_DHT22.cpp LoRaWAN_P2P_send_packets_DHT22.cpp
COPY NB_IoT.cpp NB_IoT.cpp
COPY sodaq.h sodaq.h

ENV INITSYSTEM on

CMD ["/bin/bash"

# Customise and compile

# Enable OpenRC
]
